.Dd August 10, 2026
.Dt Loaders-update 8
.Os
.Sh NAME
.Nm loaders-update
.Nd This utility helps to update the FreeBSD loaders.
.Sh SYNOPSIS
.Nm loaders-update
.Sy mode
.Op -befgnoqry
.Op -m Ar Efi_mount_dir
.Op -s Ar loaders_source_dir
.Sh DESCRIPTION
This command searches for all the FreeBSD loaders, EFI and BIOS ones.
It checks if they are in sync with the ones inside /boot or inside the argument of the -s option.
For each one which isn't, it proposes either the commands to type to update it or executes these very commands, depending on the
.Cm mode.
.Sh MODE
.D1 Cm shoot-me
This mode may update the loader(s), but ask for confirmation before each one.
You need to be root.
.Pp
.D1 Cm show-me
This mode just shows the commands to type, it changes nothing.
.Pp
.D1 Cm make-efi-failsafe
This mode, or rather command, allows to implant the EFI failsafe feature in the machine. You need to be root.
It creates an EFI boot var (labeled LU-FailSafe) that points to LU-old-loader.efi in the main ESP.
At each EFI loaders update with the
.Cm shoot-me
mode, the previous loader is saved to LU-old-loader.efi.
In case of failure of the new EFI loader for starting, you can call the boot menu and choose LU-FailSafe entry.
.It
Be aware that the manipulation of EFI vars can sometimes lead to some damages with bogus EFI firmware (typically on old machines).
.Sh OPTIONS
These options are available:
.Bl -tag -width ".Cm activate"
.It Fl b
Scan only BIOS loaders (excludes EFI loaders).
.It Fl e
Scan only EFI loaders (excludes BIOS loaders).
.It Fl f
Won't check the content of the freebsd-boot partitions.
That means it won't verify the coherence between the current root file system and each BIOS loader.
It will update the partitions according to the detected root file system.
This option cannot be chosen at the same time than -r.
.It Fl g
Use 'gpart show' instead of 'sysctl kern.disks' in order to list the available disks.
In some circumstances, the output of kern.disks doesn't match the geoms that 'gpart' knows.
So, in case of bad or no detection of your disk(s), you can try this option.
.It Fl n
Don't backup the BIOS loaders.
.It Fl o Ar Save_BIOS_loaders_dir
Specify the directory where to save the BIOS loaders. Defaut: /root.
.It Fl q
Quiet mode. No output to the console.
.It Fl m Ar Efi_mount_dir
If an efi partition isn't already mounted, try to mount it in Efi_mount_dir.
The default is /mnt.
.It Fl r
Won't check the root file system.
As -f, it won't verify the coherence between the current root file system and each BIOS loader.
It will just check the content of each freebsd-boot partition and verify/update according to that.
Can be of some use in case you rescue a system with a USB key, for example.
This option cannot be chosen at the same time than -f.
.It Fl s Ar loaders_source_dir
Seek for the source loaders in loaders_source_dir instead of the default /boot.
.It Fl y
Answer yes for shoot-me mode. Use with caution!
.Sh Return codes:
  0: no error.
  1: an error occured.
  2: at least one loader isn't up-to-date.
  3: = 1 + 2.
.El
.Sh CAPABILITIES
.It
ø Check all disks reported by the system.
.It
ø Able to work on both BIOS and UEFI loaders.
.It
ø Work on mounted or unmounted EFI partitions.
.It
ø Recognize FreeBSD EFI loaders and examine only them.
.It
ø Check each freebsd-boot partition, compare its bootcode with the root file system.
If not coherent, don't examine its content (unless -r or -f option is specified).
.It
ø If a loader is already up-to-date, neither suggest nor attempt an update.
.It
ø Systematically save the current BIOS loaders before to update them (unless option -n is selected).
.It
ø If the EFI FailSafe feature is implanted, save the previous EFI loader before to update.
.El
.Sh LIMITATIONS
.It
ø Work only on AMD64 or ARM64 architectures.
.It
ø Can only examine disks with GUID Partition Table (GPT).
.It
ø Check only the first freebsd-boot and efi partition per disk.
.El
.Sh HOW TO REMOVE THE EFI FAILSAFE FEATURE
.Pp
In case you want to remove this feature:
.It
.Dl # efibootmgr -v | grep LU-FailSafe
.Pp
You will see a line begining by Bootxxxx, note the xxxx. then:
.It
.Dl # efibootmgr -b xxxx -B
.Pp
At this point, the feature is only partially removed. The EFI loader LU-old-loader.efi is still present in the ESP. When you will invoke the 
.Cm shoot-me
mode, the previous loader will still be saved to LU-old-loader.efi. If you want to prevent this backup, mount your ESP (if not already mounted) and simply delete LU-old-loader.efi.
.El
.Sh HOW BIOS LOADERS ARE SAVED
.It
By default you will find them in /root, but you can change that with the -o option. Only the loaders that have been actually updated are saved. Their names are:
.Dl pmbr.geom and [gptzfsboot|gptboot].part_name
.Pp
Where geom is the name of the disk (e.g. ada0) for pmbr and part_name, the partition name for gptzfsboot/gptboot (e.g. ada0p2).
.It
If you need to downgrade a given geom:
.It
.Dl # gpart bootcode -b pmbr.geom geom
.It
and/or 
.It
.Dl # gpart bootcode -p [gptzfsboot|gptboot].part_name -i index diskname
.It
(In the example, diskname is ada0, index is 2)
.Sh SEE ALSO
.Xr uefi 8 ,
.Xr gpart 8 ,
.Xr gptboot 8 ,
.Xr gptzfsboot 8 ,
.Xr efibootmgr 8 ,
.Xr efivar 8
.El
.Sh COMMENTS
This utility comes to fill a void in the FreeBSD upgrading.
Many people don't even know about the importance to update the loaders and got bitten by different problems along the system upgrades.
This mainly concerns zfs on root systems, but not only.
It features to update all the loaders but also tries to stay stable in different environments and FreeBSD derivatives.
As such, it can be used in GhostBSD, TrueNas, Hardened BSD and maybe others I didn't test.
In some words, it costs nothing to run it in show-me mode and see what happens. You can report the result here: https://github.com/Emrion/uploaders or there: https://forums.freebsd.org/threads/utility-that-tries-to-figure-how-to-update-the-freebsd-loaders.94237/
